Ensure the types of BallState fields
This may have fixed a very scary numba problem that would yield
bad numba caches, leading to this error:

RuntimeError: In 'NRT_adapt_ndarray_to_python', 'descr' is NULL

I think it was due to nondeterminstic type signatures which made caching
impossible. I HOPE THIS FIXES IT